const base = require('./eslint.base');

module.exports = [
  ...base,
  {
    // Auto-generated by `next dev`/`next build`, regenerated on every run,
    // explicitly marked "should not be edited" in its own header — never a
    // real lint target, same posture as .next/ build output itself.
    ignores: ['next-env.d.ts'],
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },
];
