import { generateKeyPairSync } from 'node:crypto';
import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Local dev only. Production sources the private key from AWS Secrets
 * Manager at container boot (see .env.example) — it is never generated by
 * or committed to this repo.
 */
const keysDir = join(__dirname, '..', 'keys');
if (!existsSync(keysDir)) mkdirSync(keysDir, { recursive: true });

const { publicKey, privateKey } = generateKeyPairSync('rsa', {
  modulusLength: 2048,
  publicKeyEncoding: { type: 'spki', format: 'pem' },
  privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
});

writeFileSync(join(keysDir, 'jwt-private.pem'), privateKey, { mode: 0o600 });
writeFileSync(join(keysDir, 'jwt-public.pem'), publicKey, { mode: 0o644 });

console.log(`Generated dev RS256 keypair at ${keysDir}/jwt-{private,public}.pem`);
